<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
        <Compile Include="Program.fs" />
    </ItemGroup>
    <ItemGroup>
      <PackageReference Include="AWSSDK.Core" Version="4.0.3.12" />
      <PackageReference Include="AWSSDK.DynamoDBv2" Version="4.0.10.9" />
      <PackageReference Include="Equinox.Core" Version="4.1.1" />
      <PackageReference Include="Equinox.DynamoStore" Version="4.2.0-rc.1" />
      <PackageReference Include="Equinox" Version="4.1.0" />
      <PackageReference Include="FsCodec.NewtonsoftJson" Version="3.1.0" />
      <PackageReference Include="FsCodec.SystemTextJson" Version="3.1.0" />
      <PackageReference Include="FsCodec" Version="3.1.0" />
      <PackageReference Include="FSharp.AWS.DynamoDB" Version="0.13.0-beta" />
      <PackageReference Include="Serilog.Sinks.Console" Version="4.1" />
      <PackageReference Include="Serilog" Version="4.3" />
    </ItemGroup>
</Project>
